const actionTypes = {

  INIT_ACCOUNT_ID: 'INIT_ACCOUNT_ID',
  ACCOUNT_ID: 'ACCOUNT_ID',

  SET_ACCOUNT_IDTEXT: 'SET_ACCOUNT_IDTEXT',

  INIT_WIKI_RES: 'INIT_WIKI_RES',
  SET_WIKI_RES: 'SET_WIKI_RES',

  INIT_WIKI_IMAGE: 'INIT_WIKI_IMAGE',
  SET_WIKI_IMAGE: 'SET_WIKI_IMAGE',
};

export { actionTypes };
